name: Trading Scenario Cypress Testing

on: push

jobs:
  install-and-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: "Run Test"
        uses: cypress-io/github-action@v5
        with:
          install: false
          command: npm run test:headless